import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
    header: {
     flexDirection: 'row',
     alignItems: 'center',
     justifyContent: 'center',
     marginBottom: 20,
     position: 'relative', 
   },
   headerContent: {
     flexDirection: 'row',
     alignItems: 'center',
   },
   title: {
     fontSize: 24,
     fontWeight: 'bold',
     color: '#1a73e8',
     marginLeft: 10,
   },
   helpButton: {
     position: 'absolute',
     right: 0,
     padding: 8,
   },
   modalOverlay: {
     flex: 1,
     backgroundColor: 'rgba(0, 0, 0, 0.5)',
     justifyContent: 'center',
     alignItems: 'center',
     padding: 20,
   },
   modalContent: {
     backgroundColor: 'white',
     borderRadius: 12,
     width: '100%',
     maxHeight: '80%',
     padding: 20,
     shadowColor: '#000',
     shadowOffset: { width: 0, height: 2 },
     shadowOpacity: 0.25,
     shadowRadius: 4,
     elevation: 5,
   },
   modalHeader: {
     flexDirection: 'row',
     justifyContent: 'space-between',
     alignItems: 'center',
     marginBottom: 20,
   },
   modalTitle: {
     fontSize: 20,
     fontWeight: 'bold',
     color: '#333',
   },
   modalScroll: {
     maxHeight: '90%',
   },
   helpSectionTitle: {
     fontSize: 18,
     fontWeight: 'bold',
     color: '#1a73e8',
     marginTop: 16,
     marginBottom: 8,
   },
   helpSubtitle: {
     fontSize: 16,
     fontWeight: '600',
     color: '#333',
     marginTop: 12,
     marginBottom: 4,
   },
   helpText: {
     fontSize: 14,
     color: '#666',
     lineHeight: 20,
     marginBottom: 12,
   },
   container: {
     flex: 1,
     backgroundColor: '#f5f5f5',
   },
   scrollView: {
     flex: 1,
     padding: 16,
   },
   card: {
     backgroundColor: 'white',
     borderRadius: 12,
     padding: 20,
     marginBottom: 16,
     shadowColor: '#000',
     shadowOffset: { width: 0, height: 2 },
     shadowOpacity: 0.1,
     shadowRadius: 4,
     elevation: 3,
   },
   inputContainer: {
     marginBottom: 16,
   },  timeInputContainer: {
     flexDirection: 'row',
     alignItems: 'center',
   },
   timeInputWrapper: {
     flex: 1,
     flexDirection: 'row',
     alignItems: 'center',
   },
   label: {
     fontSize: 16,
     fontWeight: '600',
     color: '#333',
     marginBottom: 8,
   },
   inputWrapper: {
     flexDirection: 'row',
     alignItems: 'center',
   },
   input: {
     flex: 1,
     height: 48, 
     borderWidth: 1,
     borderColor: '#ddd',
     borderRadius: 8,
     paddingHorizontal: 12,
     fontSize: 16,
     textAlignVertical: 'center', 
   },
   
   inputWithSuffix: {
     borderTopRightRadius: 0,
     borderBottomRightRadius: 0,
   },
   
   suffix: {
     height: 48, 
     backgroundColor: '#f5f5f5',
     paddingHorizontal: 14,
     borderWidth: 1,
     borderLeftWidth: 0,
     borderColor: '#ddd',
     borderTopRightRadius: 8,
     borderBottomRightRadius: 8,
     color: '#666',
     textAlignVertical: 'center', 
     lineHeight: 48, 
   },
   
   unitSelector: {
     height: 48, 
     backgroundColor: '#f5f5f5',
     paddingHorizontal: 14,
     borderWidth: 1,
     borderLeftWidth: 0,
     borderColor: '#ddd',
     borderTopRightRadius: 8,
     borderBottomRightRadius: 8,
     minWidth: 60,
     justifyContent: 'center', 
   },
   
   unitText: {
     color: '#666',
     fontSize: 16,
     fontWeight: '500',
     textAlign: 'center',
   },
   
   button: {
     height: 48, 
     backgroundColor: '#1a73e8',
     borderRadius: 8,
     justifyContent: 'center', 
     alignItems: 'center',
     marginTop: 8,
   },
   buttonText: {
     color: 'white',
     fontSize: 16,
     fontWeight: '600',
   },
   resultCard: {
     backgroundColor: 'white',
     borderRadius: 12,
     padding: 20,
     marginBottom: 25,
     alignItems: 'center',
     shadowColor: '#000',
     shadowOffset: { width: 0, height: 2 },
     shadowOpacity: 0.1,
     shadowRadius: 4,
     elevation: 3,
   },
   resultTitle: {
     fontSize: 20,
     fontWeight: 'bold',
     color: '#333',
     marginBottom: 8,
   },
   componentResults: {
     width: '100%',
     marginBottom: 16,
   },
   componentText: {
     fontSize: 16,
     color: '#666',
     marginBottom: 4,
   },
   resultValue: {
     fontSize: 48,
     fontWeight: 'bold',
     color: '#1a73e8',
     marginBottom: 8,
   },
   resultStatus: {
     fontSize: 18,
     fontWeight: '600',
   },
   infoCard: {
     backgroundColor: 'white',
     borderRadius: 12,
     padding: 20,
     marginBottom: 16,
     shadowColor: '#000',
     shadowOffset: { width: 0, height: 2 },
     shadowOpacity: 0.1,
     shadowRadius: 4,
     elevation: 3,
   },
   infoTitle: {
     fontSize: 18,
     fontWeight: 'bold',
     color: '#333',
     marginBottom: 12,
   },
   infoText: {
     fontSize: 14,
     color: '#666',
     marginBottom: 8,
     lineHeight: 20,
   },
   watermarkContainer: {
    marginTop: 10,
    marginBottom: 40,
    alignItems: 'center',
  },
  watermark: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(26, 115, 232, 0.1)',
  },
  watermarkText: {
    color: '#1a73e8',
    marginLeft: 8,
    fontSize: 16,
    fontWeight: '500',
  },
 });