import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
    header: {
     flexDirection: 'row',
     alignItems: 'center',
     justifyContent: 'center',
     marginBottom: 20,
     position: 'relative', 
   },
   headerContent: {
     flexDirection: 'row',
     alignItems: 'center',
   },
   title: {
     fontSize: 24,
     fontWeight: 'bold',
     color: '#1a73e8',
     marginLeft: 10,
   },
   helpButton: {
     position: 'absolute',
     right: 0,
     padding: 8,
   },
   container: {
     flex: 1,
     backgroundColor: '#f5f5f5',
   },
   scrollView: {
     flex: 1,
     padding: 16,
   },
   card: {
     backgroundColor: 'white',
     borderRadius: 12,
     padding: 20,
     marginBottom: 16,
     shadowColor: '#000',
     shadowOffset: { width: 0, height: 2 },
     shadowOpacity: 0.1,
     shadowRadius: 4,
     elevation: 3,
   },
   inputContainer: {
     marginBottom: 16,
   },  timeInputContainer: {
     flexDirection: 'row',
     alignItems: 'center',
   },
   timeInputWrapper: {
     flex: 1,
     flexDirection: 'row',
     alignItems: 'center',
   },
   label: {
     fontSize: 16,
     fontWeight: '600',
     color: '#333',
     marginBottom: 8,
   },
   inputWrapper: {
     flexDirection: 'row',
     alignItems: 'center',
   },
   input: {
     flex: 1,
     height: 48, 
     borderWidth: 1,
     borderColor: '#ddd',
     borderRadius: 8,
     paddingHorizontal: 12,
     fontSize: 16,
     textAlignVertical: 'center', 
   },
   
   inputWithSuffix: {
     borderTopRightRadius: 0,
     borderBottomRightRadius: 0,
   },
   
   suffix: {
     height: 48, 
     backgroundColor: '#f5f5f5',
     paddingHorizontal: 14,
     borderWidth: 1,
     borderLeftWidth: 0,
     borderColor: '#ddd',
     borderTopRightRadius: 8,
     borderBottomRightRadius: 8,
     color: '#666',
     textAlignVertical: 'center', 
     lineHeight: 48, 
   },
   
   unitSelector: {
     height: 48, 
     backgroundColor: '#f5f5f5',
     paddingHorizontal: 14,
     borderWidth: 1,
     borderLeftWidth: 0,
     borderColor: '#ddd',
     borderTopRightRadius: 8,
     borderBottomRightRadius: 8,
     minWidth: 60,
     justifyContent: 'center', 
   },
   
   unitText: {
     color: '#666',
     fontSize: 16,
     fontWeight: '500',
     textAlign: 'center',
   },
   
   button: {
     height: 48, 
     backgroundColor: '#1a73e8',
     borderRadius: 8,
     justifyContent: 'center', 
     alignItems: 'center',
     marginTop: 8,
   },
   buttonText: {
     color: 'white',
     fontSize: 16,
     fontWeight: '600',
   },
   resultCard: {
     backgroundColor: 'white',
     borderRadius: 12,
     padding: 20,
     marginBottom: 25,
     alignItems: 'center',
     shadowColor: '#000',
     shadowOffset: { width: 0, height: 2 },
     shadowOpacity: 0.1,
     shadowRadius: 4,
     elevation: 3,
   },
   resultTitle: {
     fontSize: 20,
     fontWeight: 'bold',
     color: '#333',
     marginBottom: 8,
   },
   componentResults: {
     width: '100%',
     marginBottom: 16,
   },
   componentText: {
     fontSize: 16,
     color: '#666',
     marginBottom: 4,
   },
   resultValue: {
     fontSize: 48,
     fontWeight: 'bold',
     color: '#1a73e8',
     marginBottom: 8,
   },
   resultStatus: {
     fontSize: 18,
     fontWeight: '600',
   },
   infoCard: {
     backgroundColor: 'white',
     borderRadius: 12,
     padding: 20,
     marginBottom: 16,
     shadowColor: '#000',
     shadowOffset: { width: 0, height: 2 },
     shadowOpacity: 0.1,
     shadowRadius: 4,
     elevation: 3,
   },
   infoTitle: {
     fontSize: 18,
     fontWeight: 'bold',
     color: '#333',
     marginBottom: 12,
   },
   infoText: {
     fontSize: 14,
     color: '#666',
     marginBottom: 8,
     lineHeight: 20,
   },
   watermarkContainer: {
    marginTop: 10,
    marginBottom: 40,
    alignItems: 'center',
  },
  watermark: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(26, 115, 232, 0.1)',
  },
  watermarkText: {
    color: '#1a73e8',
    marginLeft: 8,
    fontSize: 16,
    fontWeight: '500',
  },
  buttonDisabled: {
    backgroundColor: '#ADD8E6',
    opacity: 0.6,
  },
    metricsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginBottom: 20,
  },
  oeeTotalContainer: {
    alignItems: 'center',
    marginTop: 10,
    
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 16,
    width: '100%',
    maxHeight: '85%',
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  modalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginLeft: 10,
  },
  closeButton: {
    padding: 5,
  },
  modalScroll: {
    maxHeight: '90%',
  },
  helpSection: {
    marginBottom: 25,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  helpSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1a73e8',
    marginLeft: 10,
  },
  helpText: {
    fontSize: 14,
    color: '#555',
    lineHeight: 22,
    marginBottom: 15,
  },
  factorContainer: {
    marginBottom: 12,
  },
  factorPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 5,
  },
  helpSubtitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#666',
  },
  factorDescription: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
    paddingLeft: 10,
    borderLeftWidth: 2,
    borderLeftColor: '#eee',
    marginLeft: 5,
  },
  formulaCard: {
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    padding: 15,
    marginTop: 5,
  },
  formulaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  formulaText: {
    fontSize: 13,
    color: '#444',
    marginLeft: 10,
    flex: 1,
  },
  formulaHighlight: {
    fontWeight: 'bold',
    color: '#1a73e8',
  },
  stepContainer: {
    flexDirection: 'row',
    marginBottom: 15,
  },
  stepIndicator: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#1a73e8',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  stepNumber: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 3,
  },
  stepDescription: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },
  standardCard: {
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    padding: 15,
  },
  standardBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  standardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginLeft: 5,
  },
  standardValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1a73e8',
    marginVertical: 3,
  },
  standardDescription: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },
  
 });